#!/bin/sh
path=$1
if [ -z $path ]; then
	path=$(pwd)
fi
if [ "${path: -1}" == "/" ]; then	
	path="${path:0: -1}"
fi

cd $path
while read -r line; do
	 result+="export * from \"./${line%.*}\"\n"
done < <(ls -d "*/" | cut -f1 -d'/')
while read -r line; do
	result+="export * from \"./${line%.*}\";\n"
done < <(ls | grep .ts)
echo -e "$result" > index.ts