#!/usr/bin/env bash
path=$1
if [ -z $path ]; then
	path=$(pwd)
fi
if [ "${path: -1}" == "/" ]; then	
	path="${path:0: -1}"
fi

cd $path
while read -r line; do
    if [[ -f "$line/index.ts" ]]; then
        result+="export * from \"./${line%.*}\"\n"
    fi
done < <(ls -d */ | cut -f1 -d'/')
while read -r line; do
    if [[ "$line" == "index.ts" ]]; then
        continue
    fi
	result+="export * from \"./${line%.*}\";\n"
done < <(ls | grep .ts)
echo -e "$result" > index.ts
