#!/bin/sh
name=$1
path=$2
if [ -z $path ]; then
	path=$(pwd)
fi
if [ "${path: -1}" == "/" ]; then	
	path="${path:0: -1}"
fi
name=${name^}
componentPath="$path/$name"
mkdir "$componentPath"

indexFile="$componentPath/index.ts"
scssFile="$componentPath/$name.scss"
tsxFile="$componentPath/$name.tsx"

touch $indexFile $scssFile $tsxFile

cat > $tsxFile << tsx
import { FC } from "react";
import "./$name.scss";

export type ${name}Props = {
   
}

export const $name: FC<${name}Props> = ({})=>{
   
   return (
      <>

      </>
   );
}
tsx

cat > $indexFile << index
export * from "./$name";
index
